[kde-base/kget-4.4.95] Drop kdenetwork-r1138807-fix-virtual-scandlg.patch
Apparently upstream included the patch again as it causes:
.../scandlg.h:65: error: ‘virtual void kt::ScanDlg::error(const QString&)’ cannot be overloaded
.../scandlg.h:62: error: with ‘virtual void kt::ScanDlg::error(const QString&)’